# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# حل مشكلة ordinal 380 في مكتبات Qt
from PyInstaller.utils.hooks import collect_dynamic_libs, collect_submodules

# جمع جميع المكتبات الديناميكية
qt_binaries = collect_dynamic_libs('PySide6')

# جمع جميع الوحدات الفرعية المهمة
all_hidden_imports = [
    'sqlalchemy',
    'sqlalchemy.ext',
    'sqlalchemy.orm',
    'sqlalchemy.sql',
    'pydantic',
    'pydantic.v1',
    'PySide6',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    'PySide6.QtSql',
    'PySide6.QtNetwork',
    'core',
    'data',
    'ui',
    'sync',
    'app',
    'hashlib',
    'bcrypt',
    'passlib',
    'passlib.hash',
    'json',
    'datetime',
    'uuid',
    'os',
    'sys',
    'typing',
    'collections',
    're',
    'decimal',
    'functools',
    'itertools',
    'logging',
    'pathlib',
    'shutil',
    'tempfile',
    'time',
    'warnings',
    'zipfile',
    'io',
    'base64',
    'csv',
    'math',
    'statistics',
    'random',
    'string',
    'textwrap',
    'inspect',
    'enum',
    'dataclasses',
    'contextlib',
    'threading',
    'multiprocessing',
    'subprocess',
    'signal',
    'atexit',
    'weakref',
    'copy',
    'pprint',
    'pickle',
    'shelve',
    'sqlite3',
    'hashlib',
    'hmac',
    'secrets',
    'binascii',
    'struct',
    'array',
    'mmap',
    'errno',
    'ctypes',
    'platform',
    'locale',
    'gettext',
    'codecs',
    'unicodedata',
    'stringprep',
    'reprlib',
    'numbers',
    'fractions',
    'decimal',
    'datetime',
    'calendar',
    'collections',
    'heapq',
    'bisect',
    'queue',
    'sched',
    'contextvars',
    'dataclasses',
    'typing',
    'pydoc',
    'doctest',
    'unittest',
    'test',
    'traceback',
    'linecache',
    'tokenize',
    'keyword',
    'token',
    'opcode',
    'dis',
    'inspect',
    'ast',
    'symtable',
    'symbol',
    'parser',
    'codeop',
    'py_compile',
    'compileall',
    'imp',
    'importlib',
    'pkgutil',
    'modulefinder',
    'runpy',
    'zipimport',
    'pkg_resources',
    'setuptools',
    'distutils',
    'ensurepip',
    'venv',
    'site',
    'sysconfig',
    '__future__',
    'builtins',
    'exceptions',
    'types',
    'warnings',
    'contextlib',
    'abc',
    'atexit',
    'copyreg',
    'gc',
    'inspect',
    'marshal',
    'posix',
    'signal',
    'sys',
    'traceback',
    'weakref',
    '_thread',
    '_dummy_thread',
    '_weakrefset',
    '_collections',
    '_collections_abc',
    '_functools',
    '_heapq',
    '_bisect',
    '_random',
    '_sha512',
    '_md5',
    '_sha1',
    '_sha256',
    '_blake2',
    '_hashlib',
    '_stat',
    '_statistics',
    '_datetime',
    '_pickle',
    '_sre',
    '_string',
    '_struct',
    '_symtable',
    '_tokenize',
    '_warnings',
    '_weakref',
    '_winapi',
    '_locale',
    '_codecs',
    '_codecs_cn',
    '_codecs_hk',
    '_codecs_iso2022',
    '_codecs_jp',
    '_codecs_kr',
    '_codecs_tw',
    '_multibytecodec',
    '_multiprocessing',
    '_queue',
    '_socket',
    '_ssl',
    '_elementtree',
    '_json',
    '_csv',
    '_decimal',
    '_pydecimal',
    '_sqlite3',
    '_bisect',
    '_heapq',
    '_random',
    '_sha512',
    '_md5',
    '_sha1',
    '_sha256',
    '_blake2',
    '_hashlib',
    '_stat',
    '_statistics',
    '_datetime',
    '_pickle',
    '_sre',
    '_string',
    '_struct',
    '_symtable',
    '_tokenize',
    '_warnings',
    '_weakref',
    '_winapi',
    '_locale',
    '_codecs',
    '_codecs_cn',
    '_codecs_hk',
    '_codecs_iso2022',
    '_codecs_jp',
    '_codecs_kr',
    '_codecs_tw',
    '_multibytecodec',
    '_multiprocessing',
    '_queue',
    '_socket',
    '_ssl',
    '_elementtree',
    '_json',
    '_csv',
    '_decimal',
    '_pydecimal',
    '_sqlite3',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=qt_binaries,
    datas=[],
    hiddenimports=all_hidden_imports,
    hookspath=[],
    hooksconfig={
        'PySide6': {
            'qt_plugins': ['platforms', 'styles', 'iconengines'],
        }
    },
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# إضافة بيانات إضافية
added_files = [
    ('app/resources/*', 'app/resources'),
    ('logs/*', 'logs'),
    ('*.bat', '.'),
]

for src, dest in added_files:
    a.datas += [(src, dest)]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='نظام_الامداد',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)